- hosts: localhost
  tasks: 
    - name: Set basic env vars
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: 'ANSIBLE_HOST_PATTERN_MISMATCH=ignore'
        create: true
      become: true
