name: Validate autoinstall config

on:
  push:
    branches: [main]
    paths:
      - 'autoinstall/autoinstall.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout Subiquity
        uses: actions/checkout@v4
        with:
          repository: canonical/subiquity
          path: subiquity

      - name: Install Subiquity dependencies
        working-directory: subiquity
        run: make install_deps

      - name: Seed a fake source catalog
        run: |
          sudo mkdir -p /cdrom/casper
          cat <<'EOF' | sudo tee /cdrom/casper/install-sources.yaml
          - id: ubuntu-desktop
            default: true
            name: {en: Ubuntu Desktop}
            description: {en: Default}
            size: 1
            path: x.squashfs
            type: fsimage
            variant: desktop
          - id: ubuntu-desktop-minimal
            name: {en: Ubuntu Desktop minimal}
            description: {en: Minimal}
            size: 1
            path: y.squashfs
            type: fsimage
            variant: desktop
          EOF

      - name: Validate autoinstall.yml
        working-directory: subiquity
        run: |
          ./scripts/validate-autoinstall-user-data.py \
            --no-expect-cloudconfig -vvv \
            ../autoinstall/autoinstall.yml

